#!/bin/bash

# Script de test pour le dispatch proportionnel
# Charge les données de test et affiche les instructions

echo "=============================================="
echo "  TEST DU DISPATCH PROPORTIONNEL"
echo "=============================================="
echo ""
echo "1. Chargement des données de test..."

# Charger les données
mysql -u root < "./script/insertion/2026-02-17_test_proportionnel.sql"

if [ $? -eq 0 ]; then
    echo "   ✓ Données chargées avec succès"
    echo ""
    echo "=============================================="
    echo "  DONNÉES CHARGÉES :"
    echo "=============================================="
    echo ""
    echo "CAS 1 : Riz"
    echo "  - Stock disponible : 5 kg"
    echo "  - Demandes :"
    echo "    • Ville Alpha : 1 kg"
    echo "    • Ville Beta  : 3 kg"
    echo "    • Ville Gamma : 3 kg"
    echo "    • TOTAL       : 7 kg"
    echo ""
    echo "  RÉSULTAT ATTENDU :"
    echo "    • Ville Alpha : 1 kg (0.714 + 1 reste)"
    echo "    • Ville Beta  : 2 kg"
    echo "    • Ville Gamma : 2 kg"
    echo "    • TOTAL       : 5 kg ✓"
    echo ""
    echo "CAS 2 : Argent"
    echo "  - Stock disponible : 250,000 Ar"
    echo "  - Demandes :"
    echo "    • Ville Alpha : 100,000 Ar"
    echo "    • Ville Beta  : 100,000 Ar"
    echo "    • Ville Gamma : 100,000 Ar"
    echo "    • TOTAL       : 300,000 Ar"
    echo ""
    echo "  RÉSULTAT ATTENDU :"
    echo "    • Ville Alpha : 83,334 Ar"
    echo "    • Ville Beta  : 83,333 Ar"
    echo "    • Ville Gamma : 83,333 Ar"
    echo "    • TOTAL       : 250,000 Ar ✓"
    echo ""
    echo "CAS 3 : Tôles"
    echo "  - Stock disponible : 20 tôles"
    echo "  - Demandes :"
    echo "    • Ville Alpha : 5 tôles"
    echo "    • Ville Beta  : 10 tôles"
    echo "    • Ville Gamma : 15 tôles"
    echo "    • TOTAL       : 30 tôles"
    echo ""
    echo "  RÉSULTAT ATTENDU :"
    echo "    • Ville Alpha : 3 tôles"
    echo "    • Ville Beta  : 7 tôles"
    echo "    • Ville Gamma : 10 tôles"
    echo "    • TOTAL       : 20 tôles ✓"
    echo ""
    echo "=============================================="
    echo "  INSTRUCTIONS POUR TESTER :"
    echo "=============================================="
    echo ""
    echo "1. Ouvrir le navigateur et aller sur votre site BNGRC"
    echo ""
    echo "2. Aller sur la page 'Dispatch des dons'"
    echo ""
    echo "3. Sélectionner la stratégie 'Proportionnelle'"
    echo ""
    echo "4. Cliquer sur 'Dispatcher'"
    echo ""
    echo "5. Vérifier que les résultats correspondent aux"
    echo "   distributions attendues ci-dessus"
    echo ""
    echo "6. Pour voir les détails, aller sur 'Historique'"
    echo ""
    echo "=============================================="
    echo ""
    echo "✓ Script terminé avec succès"
    echo ""
else
    echo "   ✗ Erreur lors du chargement des données"
    echo ""
    echo "Vérifiez que MySQL est démarré et que la base"
    echo "de données 'bngrc' existe."
    exit 1
fi
